// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjGICrTefEHTiRJiZjwWSAo4BpebXScwU',
    appId: '1:283459907128:web:1c6db2a086b7a46ee500cd',
    messagingSenderId: '283459907128',
    projectId: 'amd-app-bbd5c',
    authDomain: 'amd-app-bbd5c.firebaseapp.com',
    storageBucket: 'amd-app-bbd5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuva7DY2tjwudrR_75PW9pCVzFAipI9vQ',
    appId: '1:283459907128:android:8c2632001811dd23e500cd',
    messagingSenderId: '283459907128',
    projectId: 'amd-app-bbd5c',
    storageBucket: 'amd-app-bbd5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUcNE9sKWsI9TQgJ945IZP2Hkp5H6Ac4M',
    appId: '1:283459907128:ios:69fc677685b0dd91e500cd',
    messagingSenderId: '283459907128',
    projectId: 'amd-app-bbd5c',
    storageBucket: 'amd-app-bbd5c.firebasestorage.app',
    iosBundleId: 'com.example.amdAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUcNE9sKWsI9TQgJ945IZP2Hkp5H6Ac4M',
    appId: '1:283459907128:ios:69fc677685b0dd91e500cd',
    messagingSenderId: '283459907128',
    projectId: 'amd-app-bbd5c',
    storageBucket: 'amd-app-bbd5c.firebasestorage.app',
    iosBundleId: 'com.example.amdAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjGICrTefEHTiRJiZjwWSAo4BpebXScwU',
    appId: '1:283459907128:web:a2caacb5204d5bd2e500cd',
    messagingSenderId: '283459907128',
    projectId: 'amd-app-bbd5c',
    authDomain: 'amd-app-bbd5c.firebaseapp.com',
    storageBucket: 'amd-app-bbd5c.firebasestorage.app',
  );
}
